class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _strings = {
    // ===== عام =====
    'app_name': {'ar': 'All Owners', 'en': 'All Owners'},
    'app_tagline': {'ar': 'فندقك، أينما كنت', 'en': 'Your stay, anywhere'},
    'continue': {'ar': 'استمرار', 'en': 'Continue'},
    'next': {'ar': 'التالي', 'en': 'Next'},
    'skip': {'ar': 'تخطي', 'en': 'Skip'},
    'back': {'ar': 'رجوع', 'en': 'Back'},
    'cancel': {'ar': 'إلغاء', 'en': 'Cancel'},
    'confirm': {'ar': 'تأكيد', 'en': 'Confirm'},
    'save': {'ar': 'حفظ', 'en': 'Save'},
    'search': {'ar': 'بحث', 'en': 'Search'},
    'see_all': {'ar': 'عرض الكل', 'en': 'See all'},
    'loading': {'ar': 'جاري التحميل...', 'en': 'Loading...'},
    'night': {'ar': 'ليلة', 'en': 'night'},
    'nights': {'ar': 'ليالٍ', 'en': 'nights'},
    'guests': {'ar': 'ضيوف', 'en': 'guests'},
    'sar': {'ar': 'ريال', 'en': 'SAR'},

    // ===== Onboarding =====
    'onboard_title_1': {'ar': 'اكتشف أفضل الفنادق', 'en': 'Discover Top Hotels'},
    'onboard_desc_1': {
      'ar': 'فنادق وشقق فندقية مختارة بعناية في أفضل المواقع',
      'en': 'Carefully selected hotels and serviced apartments in prime locations'
    },
    'onboard_title_2': {'ar': 'حجز سهل وسريع', 'en': 'Easy & Fast Booking'},
    'onboard_desc_2': {
      'ar': 'اختر تواريخك، قارن الأسعار، واحجز بضغطة واحدة',
      'en': 'Pick your dates, compare prices, and book in one tap'
    },
    'onboard_title_3': {'ar': 'دفع مرن وآمن', 'en': 'Flexible & Secure Payment'},
    'onboard_desc_3': {
      'ar': 'ادفع الآن إلكترونياً أو عند الوصول، كما يناسبك',
      'en': 'Pay online now or at the property, whichever suits you'
    },
    'get_started': {'ar': 'ابدأ الآن', 'en': 'Get Started'},

    // ===== Auth =====
    'login': {'ar': 'تسجيل الدخول', 'en': 'Login'},
    'register': {'ar': 'إنشاء حساب', 'en': 'Register'},
    'welcome_back': {'ar': 'مرحباً بعودتك', 'en': 'Welcome Back'},
    'login_subtitle': {'ar': 'سجّل دخولك للمتابعة', 'en': 'Sign in to continue'},
    'phone_number': {'ar': 'رقم الهاتف', 'en': 'Phone Number'},
    'email': {'ar': 'البريد الإلكتروني', 'en': 'Email'},
    'password': {'ar': 'كلمة المرور', 'en': 'Password'},
    'full_name': {'ar': 'الاسم الكامل', 'en': 'Full Name'},
    'forgot_password': {'ar': 'نسيت كلمة المرور؟', 'en': 'Forgot Password?'},
    'no_account': {'ar': 'ليس لديك حساب؟', 'en': "Don't have an account?"},
    'have_account': {'ar': 'لديك حساب؟', 'en': 'Already have an account?'},
    'create_account': {'ar': 'إنشاء حساب جديد', 'en': 'Create New Account'},
    'or_continue_with': {'ar': 'أو الاستمرار باستخدام', 'en': 'Or continue with'},
    'continue_as_guest': {'ar': 'الاستمرار كزائر', 'en': 'Continue as Guest'},

    // ===== Home =====
    'home': {'ar': 'الرئيسية', 'en': 'Home'},
    'hello': {'ar': 'مرحباً', 'en': 'Hello'},
    'where_to': {'ar': 'وين بتحب تسافر؟', 'en': 'Where are you going?'},
    'search_destination': {'ar': 'ابحث عن مدينة أو فندق', 'en': 'Search city or hotel'},
    'check_in': {'ar': 'تاريخ الوصول', 'en': 'Check-in'},
    'check_out': {'ar': 'تاريخ المغادرة', 'en': 'Check-out'},
    'categories': {'ar': 'التصنيفات', 'en': 'Categories'},
    'hotels': {'ar': 'فنادق', 'en': 'Hotels'},
    'apartments': {'ar': 'شقق فندقية', 'en': 'Apartments'},
    'resorts': {'ar': 'منتجعات', 'en': 'Resorts'},
    'chalets': {'ar': 'شاليهات', 'en': 'Chalets'},
    'featured_deals': {'ar': 'عروض مميزة', 'en': 'Featured Deals'},
    'popular_destinations': {'ar': 'وجهات شائعة', 'en': 'Popular Destinations'},
    'recommended_for_you': {'ar': 'موصى به لك', 'en': 'Recommended for You'},
    'per_night': {'ar': '/ليلة', 'en': '/night'},

    // ===== Search & Filters =====
    'search_results': {'ar': 'نتائج البحث', 'en': 'Search Results'},
    'results_found': {'ar': 'نتيجة', 'en': 'results found'},
    'filters': {'ar': 'الفلاتر', 'en': 'Filters'},
    'sort_by': {'ar': 'ترتيب حسب', 'en': 'Sort by'},
    'price_range': {'ar': 'نطاق السعر', 'en': 'Price Range'},
    'star_rating': {'ar': 'تصنيف النجوم', 'en': 'Star Rating'},
    'property_type': {'ar': 'نوع العقار', 'en': 'Property Type'},
    'amenities': {'ar': 'المرافق', 'en': 'Amenities'},
    'apply_filters': {'ar': 'تطبيق الفلاتر', 'en': 'Apply Filters'},
    'reset': {'ar': 'إعادة تعيين', 'en': 'Reset'},
    'no_results': {'ar': 'لا توجد نتائج مطابقة', 'en': 'No matching results'},
    'price_low_high': {'ar': 'السعر: من الأقل للأعلى', 'en': 'Price: Low to High'},
    'price_high_low': {'ar': 'السعر: من الأعلى للأقل', 'en': 'Price: High to Low'},
    'top_rated': {'ar': 'الأعلى تقييماً', 'en': 'Top Rated'},
    'distance': {'ar': 'الأقرب', 'en': 'Nearest'},

    // ===== Hotel Details =====
    'overview': {'ar': 'نظرة عامة', 'en': 'Overview'},
    'rooms': {'ar': 'الغرف', 'en': 'Rooms'},
    'reviews': {'ar': 'تقييم', 'en': 'reviews'},
    'location': {'ar': 'الموقع', 'en': 'Location'},
    'show_more': {'ar': 'عرض المزيد', 'en': 'Show more'},
    'show_less': {'ar': 'عرض أقل', 'en': 'Show less'},
    'about_property': {'ar': 'عن العقار', 'en': 'About this property'},
    'available_rooms': {'ar': 'الغرف المتاحة', 'en': 'Available Rooms'},
    'select_room': {'ar': 'اختر الغرفة', 'en': 'Select Room'},
    'free_cancellation': {'ar': 'إلغاء مجاني', 'en': 'Free cancellation'},
    'breakfast_included': {'ar': 'الإفطار مشمول', 'en': 'Breakfast included'},
    'pay_at_property': {'ar': 'الدفع بالفندق متاح', 'en': 'Pay at the property'},
    'view_on_map': {'ar': 'عرض على الخريطة', 'en': 'View on map'},
    'guest_reviews': {'ar': 'تقييمات الضيوف', 'en': 'Guest Reviews'},
    'see_all_reviews': {'ar': 'عرض كل التقييمات', 'en': 'See all reviews'},
    'select_dates': {'ar': 'اختر تواريخك', 'en': 'Select Your Dates'},
    'book_now': {'ar': 'احجز الآن', 'en': 'Book Now'},

    // ===== Booking =====
    'booking_summary': {'ar': 'ملخص الحجز', 'en': 'Booking Summary'},
    'your_stay': {'ar': 'مدة إقامتك', 'en': 'Your Stay'},
    'guest_details': {'ar': 'بيانات الضيف', 'en': 'Guest Details'},
    'payment_method': {'ar': 'طريقة الدفع', 'en': 'Payment Method'},
    'pay_online': {'ar': 'الدفع الإلكتروني الآن', 'en': 'Pay Online Now'},
    'pay_at_hotel': {'ar': 'الدفع عند الوصول بالفندق', 'en': 'Pay at the Hotel'},
    'card_number': {'ar': 'رقم البطاقة', 'en': 'Card Number'},
    'expiry_date': {'ar': 'تاريخ الانتهاء', 'en': 'Expiry Date'},
    'cvv': {'ar': 'رمز الأمان CVV', 'en': 'CVV'},
    'cardholder_name': {'ar': 'اسم حامل البطاقة', 'en': 'Cardholder Name'},
    'price_details': {'ar': 'تفاصيل السعر', 'en': 'Price Details'},
    'room_price': {'ar': 'سعر الغرفة', 'en': 'Room Price'},
    'taxes_fees': {'ar': 'الضرائب والرسوم', 'en': 'Taxes & Fees'},
    'total_price': {'ar': 'الإجمالي', 'en': 'Total Price'},
    'confirm_booking': {'ar': 'تأكيد الحجز', 'en': 'Confirm Booking'},
    'booking_success': {'ar': 'تم تأكيد حجزك بنجاح', 'en': 'Your booking is confirmed'},
    'booking_success_desc': {
      'ar': 'تفاصيل حجزك جاهزة، نتمنى لك رحلة سعيدة',
      'en': 'Your booking details are ready. Have a great trip!'
    },
    'booking_reference': {'ar': 'رقم الحجز', 'en': 'Booking Reference'},
    'view_booking': {'ar': 'عرض الحجز', 'en': 'View Booking'},

    // ===== My Bookings =====
    'my_bookings': {'ar': 'حجوزاتي', 'en': 'My Bookings'},
    'upcoming': {'ar': 'القادمة', 'en': 'Upcoming'},
    'past': {'ar': 'السابقة', 'en': 'Past'},
    'cancelled': {'ar': 'ملغية', 'en': 'Cancelled'},
    'no_bookings_yet': {'ar': 'لا توجد حجوزات حتى الآن', 'en': 'No bookings yet'},
    'cancel_booking': {'ar': 'إلغاء الحجز', 'en': 'Cancel Booking'},
    'confirm_cancel_booking': {'ar': 'هل أنت متأكد من إلغاء هذا الحجز؟', 'en': 'Are you sure you want to cancel this booking?'},
    'booking_details': {'ar': 'تفاصيل الحجز', 'en': 'Booking Details'},

    // ===== Favorites =====
    'favorites': {'ar': 'المفضلة', 'en': 'Favorites'},
    'no_favorites_yet': {'ar': 'لم تضف أي فندق للمفضلة بعد', 'en': 'No favorites yet'},

    // ===== Profile =====
    'profile': {'ar': 'حسابي', 'en': 'Profile'},
    'edit_profile': {'ar': 'تعديل الملف الشخصي', 'en': 'Edit Profile'},
    'payment_methods': {'ar': 'وسائل الدفع', 'en': 'Payment Methods'},
    'notifications': {'ar': 'الإشعارات', 'en': 'Notifications'},
    'language': {'ar': 'اللغة', 'en': 'Language'},
    'settings': {'ar': 'الإعدادات', 'en': 'Settings'},
    'help_support': {'ar': 'المساعدة والدعم', 'en': 'Help & Support'},
    'about_us': {'ar': 'عن التطبيق', 'en': 'About Us'},
    'logout': {'ar': 'تسجيل الخروج', 'en': 'Logout'},

    // ===== Navigation =====
    'nav_home': {'ar': 'الرئيسية', 'en': 'Home'},
    'nav_search': {'ar': 'بحث', 'en': 'Search'},
    'nav_bookings': {'ar': 'حجوزاتي', 'en': 'Bookings'},
    'nav_favorites': {'ar': 'المفضلة', 'en': 'Favorites'},
    'nav_profile': {'ar': 'حسابي', 'en': 'Profile'},

    // ===== Hotel Services =====
    'available_services': {'ar': 'الخدمات المتاحة', 'en': 'Available Services'},
    'hotel_services': {'ar': 'خدمات الفندق', 'en': 'Hotel Services'},
    'maintenance': {'ar': 'الصيانة', 'en': 'Maintenance'},
    'maintenance_desc': {
      'ar': 'اطلب فني للإصلاحات داخل الغرفة',
      'en': 'Request a technician for in-room repairs'
    },
    'housekeeping': {'ar': 'الهاوس كيبنج', 'en': 'Housekeeping'},
    'housekeeping_desc': {
      'ar': 'اطلب تنظيف الغرفة أو تغيير المناشف',
      'en': 'Request room cleaning or fresh towels'
    },
    'cancellation_request': {'ar': 'طلب إلغاء', 'en': 'Cancellation Request'},
    'cancellation_request_desc': {
      'ar': 'تقديم طلب إلغاء حجز أو خدمة',
      'en': 'Submit a booking or service cancellation request'
    },
    'room_number': {'ar': 'رقم الغرفة', 'en': 'Room Number'},
    'request_details': {'ar': 'تفاصيل الطلب', 'en': 'Request Details'},
    'describe_request': {'ar': 'اكتب تفاصيل طلبك هنا...', 'en': 'Describe your request here...'},
    'submit_request': {'ar': 'إرسال الطلب', 'en': 'Submit Request'},
    'request_submitted_title': {'ar': 'تم استلام طلبك', 'en': 'Request Received'},
    'request_submitted_desc': {
      'ar': 'سيقوم فريق الفندق بمتابعة طلبك في أقرب وقت ممكن',
      'en': 'The hotel team will follow up on your request as soon as possible'
    },
    'room_number_required': {'ar': 'الرجاء إدخال رقم الغرفة', 'en': 'Please enter your room number'},
    'ok': {'ar': 'حسناً', 'en': 'OK'},
    'order_meal': {'ar': 'طلب وجبة', 'en': 'Order a Meal'},
    'order_meal_desc': {
      'ar': 'اطلب وجبتك المفضلة وسيقوم فريق الفندق بتحضيرها',
      'en': 'Order your favorite meal and the hotel team will prepare it'
    },
    'meal_type': {'ar': 'نوع الوجبة', 'en': 'Meal Type'},
    'meal_option_none': {'ar': 'بدون وجبات', 'en': 'No meals'},
    'meal_option_breakfast': {'ar': 'فطور', 'en': 'Breakfast'},
    'meal_option_lunch': {'ar': 'غداء', 'en': 'Lunch'},
    'meal_option_dinner': {'ar': 'عشاء', 'en': 'Dinner'},
    'meal_option_all': {'ar': 'جميع الوجبات', 'en': 'All meals'},
    'add_extra_bed': {'ar': 'إضافة سرير إضافي', 'en': 'Add extra bed'},
    'free': {'ar': 'مجاني', 'en': 'Free'},
    'breakfast': {'ar': 'فطور', 'en': 'Breakfast'},
    'lunch': {'ar': 'غداء', 'en': 'Lunch'},
    'dinner': {'ar': 'عشاء', 'en': 'Dinner'},
    'meal_type_required': {'ar': 'الرجاء اختيار نوع الوجبة', 'en': 'Please select a meal type'},
    'notes': {'ar': 'ملاحظات', 'en': 'Notes'},
    'notes_hint': {
      'ar': 'اكتب ملاحظاتك هنا... (مثال: بدون سكر، حساسية من المكسرات)',
      'en': 'Write your notes here... (e.g. no sugar, nut allergy)'
    },

    // ===== Roles & Owner Dashboard =====
    'account_type': {'ar': 'نوع الحساب', 'en': 'Account Type'},
    'role_owner': {'ar': 'مالك', 'en': 'Owner'},
    'role_guest': {'ar': 'ضيف', 'en': 'Guest'},
    'coming_soon_desc': {
      'ar': 'هذه الميزة قيد التطوير وستكون متوفرة قريباً',
      'en': 'This feature is under development and will be available soon'
    },
    'nav_units': {'ar': 'وحداتي', 'en': 'My Units'},
    'nav_revenue': {'ar': 'الإيرادات', 'en': 'Revenue'},
    'quick_links': {'ar': 'روابط سريعة', 'en': 'Quick Links'},
    'owner_bookings': {'ar': 'الحجوزات', 'en': 'Bookings'},
    'financial_reports': {'ar': 'التقارير المالية', 'en': 'Financial Reports'},
    'contracts_docs': {'ar': 'العقود والمستندات', 'en': 'Contracts & Documents'},
    'maintenance_requests': {'ar': 'طلبات الصيانة', 'en': 'Maintenance Requests'},
    'voting_decisions': {'ar': 'التصويت والقرارات', 'en': 'Voting & Decisions'},
    'owners_community': {'ar': 'مجتمع الملاك', 'en': 'Owners Community'},
    'units_marketplace': {'ar': 'سوق الوحدات', 'en': 'Units Marketplace'},
    'messages': {'ar': 'الرسائل', 'en': 'Messages'},
    'staff': {'ar': 'الموظفون', 'en': 'Staff'},
    'staff_desc': {
      'ar': 'أضف مدير وحدة يدخل التطبيق باسمه، يستقبل بلاغات النظافة والصيانة، ويقدر يبدّل حالة الوحدة فقط',
      'en': 'Add a unit manager who logs in with their own account, receives housekeeping/maintenance reports, and can only toggle unit status'
    },
    'add_unit_manager': {'ar': 'إضافة مدير وحدة', 'en': 'Add Unit Manager'},
    'role_unit_manager': {'ar': 'مدير الوحدة', 'en': 'Unit Manager'},
    'role_hotel_manager': {'ar': 'إدارة الفندق', 'en': 'Hotel Management'},
    'role_booking_agent': {'ar': 'وكيل الحجوزات', 'en': 'Booking Agent'},
    'staff_permissions_note': {
      'ar': 'صلاحياته تلقائياً: مشاهدة الوحدات وتبديل حالتها، واستقبال بلاغات الصيانة والتنظيف. بدون حذف، وبدون أي وصول للمحفظة أو الإيرادات أو التقارير.',
      'en': 'Automatic permissions: view units and toggle their status, and receive maintenance/housekeeping reports. No delete, and no access to wallet, revenue, or reports.'
    },
    'password_hint_min6': {'ar': '6 أحرف على الأقل', 'en': 'At least 6 characters'},
    'no_staff_yet': {'ar': 'ما في موظفين مضافين بعد', 'en': 'No staff added yet'},
    'suspended': {'ar': 'موقوف', 'en': 'Suspended'},
    'suspend': {'ar': 'إيقاف', 'en': 'Suspend'},
    'activate': {'ar': 'تفعيل', 'en': 'Activate'},
    'reset_password': {'ar': 'كلمة المرور', 'en': 'Password'},
    'occupied': {'ar': 'مؤجرة', 'en': 'Occupied'},
    'vacant': {'ar': 'متاحة', 'en': 'Vacant'},
    'monthly_revenue': {'ar': 'الإيراد الشهري', 'en': 'Monthly Revenue'},
    'total_revenue_month': {'ar': 'إجمالي إيرادات هذا الشهر', 'en': 'Total Revenue This Month'},
    'revenue_history': {'ar': 'سجل الإيرادات', 'en': 'Revenue History'},
    'retry': {'ar': 'إعادة المحاولة', 'en': 'Retry'},
    'no_data': {'ar': 'لا توجد بيانات بعد', 'en': 'No data yet'},
    'error_loading': {'ar': 'حدث خطأ أثناء تحميل البيانات', 'en': 'Something went wrong loading the data'},
    'new_request': {'ar': 'طلب جديد', 'en': 'New Request'},
    'request_title': {'ar': 'عنوان الطلب', 'en': 'Request Title'},
    'description': {'ar': 'الوصف', 'en': 'Description'},
    'submit': {'ar': 'إرسال', 'en': 'Submit'},
    'send': {'ar': 'إرسال', 'en': 'Send'},
    'select_hotel': {'ar': 'اختر الفندق', 'en': 'Select Hotel'},
    'mark_all_read': {'ar': 'تعليم الكل كمقروء', 'en': 'Mark all as read'},
    'no_notifications': {'ar': 'لا توجد إشعارات', 'en': 'No notifications'},
    'no_bookings': {'ar': 'لا توجد حجوزات بعد', 'en': 'No bookings yet'},
    'no_units': {'ar': 'لا توجد وحدات بعد', 'en': 'No units yet'},
    'no_maintenance': {'ar': 'لا توجد طلبات صيانة', 'en': 'No maintenance requests'},
    'meal_requests': {'ar': 'طلبات الوجبات', 'en': 'Meal Requests'},
    'no_meal_requests': {'ar': 'لا توجد طلبات وجبات حالياً', 'en': 'No meal requests yet'},
    'meal_breakfast': {'ar': 'فطور', 'en': 'Breakfast'},
    'meal_lunch': {'ar': 'غداء', 'en': 'Lunch'},
    'meal_dinner': {'ar': 'عشاء', 'en': 'Dinner'},
    'meal_status_pending': {'ar': 'قيد الانتظار', 'en': 'Pending'},
    'meal_status_preparing': {'ar': 'يتم التحضير', 'en': 'Preparing'},
    'meal_status_delivered': {'ar': 'تم التسليم', 'en': 'Delivered'},
    'meal_status_cancelled': {'ar': 'ملغي', 'en': 'Cancelled'},
    'room': {'ar': 'غرفة', 'en': 'Room'},
    'mark_preparing': {'ar': 'بدء التحضير', 'en': 'Start Preparing'},
    'mark_delivered': {'ar': 'تم التسليم', 'en': 'Mark Delivered'},
    'guest': {'ar': 'الضيف', 'en': 'Guest'},
    'total_amount': {'ar': 'الإجمالي', 'en': 'Total'},
    'request_sent': {'ar': 'تم إرسال الطلب بنجاح', 'en': 'Request sent successfully'},
    'by_unit': {'ar': 'حسب الوحدة', 'en': 'By Unit'},
    'pending_bookings': {'ar': 'حجوزات قيد الانتظار', 'en': 'Pending Bookings'},
    'status_open': {'ar': 'مفتوح', 'en': 'Open'},
    'status_in_progress': {'ar': 'قيد التنفيذ', 'en': 'In Progress'},
    'status_closed': {'ar': 'مغلق', 'en': 'Closed'},
    'status_pending': {'ar': 'قيد الانتظار', 'en': 'Pending'},
    'status_confirmed': {'ar': 'مؤكد', 'en': 'Confirmed'},
    'status_completed': {'ar': 'مكتمل', 'en': 'Completed'},
    'status_cancelled': {'ar': 'ملغى', 'en': 'Cancelled'},
    'status_checked_in': {'ar': 'تم تسجيل الدخول', 'en': 'Checked In'},

    // ===== Documents (Contracts) =====
    'no_documents': {'ar': 'لا توجد مستندات بعد', 'en': 'No documents yet'},
    'view_document': {'ar': 'عرض المستند', 'en': 'View'},
    'general': {'ar': 'عام', 'en': 'General'},

    // ===== Decisions (Voting) =====
    'no_decisions': {'ar': 'لا توجد قرارات مطروحة للتصويت', 'en': 'No decisions open for voting'},
    'vote_now': {'ar': 'صوّت الآن', 'en': 'Vote Now'},
    'you_voted': {'ar': 'لقد صوّتّ', 'en': 'You voted'},
    'votes_count': {'ar': 'صوت', 'en': 'votes'},
    'decision_open': {'ar': 'مفتوح للتصويت', 'en': 'Open for voting'},
    'decision_closed': {'ar': 'انتهى التصويت', 'en': 'Voting closed'},
    'vote_submitted': {'ar': 'تم تسجيل صوتك', 'en': 'Your vote has been recorded'},
    'new_decision': {'ar': 'قرار جديد للتصويت', 'en': 'New Decision'},
    'decision_title': {'ar': 'عنوان القرار', 'en': 'Decision Title'},
    'voting_options': {'ar': 'خيارات التصويت', 'en': 'Voting Options'},
    'option_label': {'ar': 'خيار', 'en': 'Option'},
    'add_option': {'ar': 'إضافة خيار', 'en': 'Add option'},
    'decision_created': {'ar': 'تم إنشاء القرار للتصويت', 'en': 'Decision created for voting'},
    'no_hotels_linked': {'ar': 'ما في فنادق مرتبطة بحسابك حالياً', 'en': 'No hotels linked to your account yet'},
    'no_units_available': {'ar': 'ما في وحدات مسجّلة بحسابك بعد لعرضها', 'en': 'You have no units yet to list'},
    'nightly_rental_hint': {'ar': 'اختر إحدى وحداتك وحدد سعر الليلة، بيقدر باقي الملاك يشوفوها ويحجزوها', 'en': "Pick one of your units and set a nightly rate for other owners to book"},
    'select_unit': {'ar': 'اختر الوحدة', 'en': 'Select Unit'},
    'price_per_night': {'ar': 'السعر بالليلة', 'en': 'Price per night'},
    'no_hotel_linked': {
      'ar': 'لا يوجد فندق مربوط بحسابك بعد. تواصل مع الإدارة لربط فندقك بحسابك.',
      'en': 'No hotel is linked to your account yet. Contact the admin to link your hotel.'
    },
    'add_unit': {'ar': 'إضافة وحدة', 'en': 'Add Unit'},
    'unit_name_ar': {'ar': 'اسم الوحدة (عربي)', 'en': 'Unit Name (Arabic)'},
    'unit_name_en': {'ar': 'اسم الوحدة (إنجليزي)', 'en': 'Unit Name (English)'},
    'unit_number': {'ar': 'رقم الوحدة', 'en': 'Unit Number'},
    'description_ar': {'ar': 'الوصف (عربي)', 'en': 'Description (Arabic)'},
    'description_en': {'ar': 'الوصف (إنجليزي)', 'en': 'Description (English)'},
    'capacity': {'ar': 'السعة', 'en': 'Capacity'},
    'price_per_week_optional': {'ar': 'السعر بالأسبوع (اختياري)', 'en': 'Price / week (optional)'},
    'price_per_month_optional': {'ar': 'السعر بالشهر (اختياري)', 'en': 'Price / month (optional)'},
    'cover_image': {'ar': 'الصورة الرئيسية', 'en': 'Cover image'},
    'hotel': {'ar': 'الفندق', 'en': 'Hotel'},
    'required_field': {'ar': 'هاد الحقل مطلوب', 'en': 'This field is required'},
    'add_unit_more_options_web': {
      'ar': 'تقدر تضيف صور إضافية، فترات إتاحة، وخيارات (سرير إضافي/وجبات) لهالوحدة لاحقاً من موقع الويب.',
      'en': 'You can add more photos, availability periods, and add-ons (extra bed/meals) for this unit later from the website.'
    },
    'unit_added_success': {'ar': 'تمت إضافة الوحدة بنجاح', 'en': 'Unit added successfully'},
    'extra_note': {'ar': 'ملاحظة إضافية (اختياري)', 'en': 'Extra note (optional)'},
    'price_prefilled_hint': {'ar': 'مُعبّى تلقائياً من سعر الوحدة، تقدر تعدله', 'en': 'Auto-filled from the unit price, you can edit it'},
    'fill_required_fields': {'ar': 'الرجاء تعبئة العنوان وخيارين على الأقل', 'en': 'Please fill the title and at least 2 options'},

    // ===== Community =====
    'no_posts': {'ar': 'لا توجد منشورات بعد، كن أول من ينشر', 'en': 'No posts yet — be the first to share'},
    'write_post': {'ar': 'اكتب منشوراً...', 'en': 'Write a post...'},
    'post': {'ar': 'نشر', 'en': 'Post'},
    'comments': {'ar': 'تعليقات', 'en': 'Comments'},
    'write_comment': {'ar': 'اكتب تعليقاً...', 'en': 'Write a comment...'},
    'like': {'ar': 'إعجاب', 'en': 'Like'},

    // ===== Marketplace =====
    'no_listings': {'ar': 'لا توجد وحدات معروضة حالياً', 'en': 'No listings yet'},
    'add_listing': {'ar': 'أضف عرضاً', 'en': 'Add Listing'},
    'listing_title': {'ar': 'عنوان العرض', 'en': 'Listing Title'},
    'listing_type': {'ar': 'نوع العرض', 'en': 'Listing Type'},
    'for_sale': {'ar': 'للبيع', 'en': 'For Sale'},
    'for_rent': {'ar': 'للإيجار', 'en': 'For Rent'},
    'price': {'ar': 'السعر', 'en': 'Price'},
    'im_interested': {'ar': 'أنا مهتم', 'en': "I'm Interested"},
    'interest_sent': {'ar': 'تم إرسال اهتمامك للمالك', 'en': 'Your interest was sent to the owner'},
    'property_apartment': {'ar': 'شقة', 'en': 'Apartment'},
    'property_studio': {'ar': 'استوديو', 'en': 'Studio'},
    'property_villa': {'ar': 'فيلا', 'en': 'Villa'},
    'property_room': {'ar': 'غرفة', 'en': 'Room'},
    'property_chalet': {'ar': 'شاليه', 'en': 'Chalet'},
    'property_commercial': {'ar': 'تجاري', 'en': 'Commercial'},
    'property_land': {'ar': 'أرض', 'en': 'Land'},
    'property_other': {'ar': 'أخرى', 'en': 'Other'},
    'area_sqm': {'ar': 'المساحة (م²)', 'en': 'Area (sqm)'},
    'bedrooms': {'ar': 'غرف النوم', 'en': 'Bedrooms'},
    'bathrooms': {'ar': 'الحمامات', 'en': 'Bathrooms'},
    'floor_number': {'ar': 'الطابق', 'en': 'Floor'},
    'furnished': {'ar': 'مفروش', 'en': 'Furnished'},
    'negotiable': {'ar': 'السعر قابل للتفاوض', 'en': 'Price negotiable'},
    'location_area': {'ar': 'الموقع / الحي', 'en': 'Location / Area'},
    'contact_number': {'ar': 'رقم التواصل (اختياري)', 'en': 'Contact number (optional)'},
    'sqm_short': {'ar': 'م²', 'en': 'sqm'},
    'more_details': {'ar': 'تفاصيل إضافية', 'en': 'More details'},
    'basic_info': {'ar': 'معلومات أساسية', 'en': 'Basic info'},

    // ===== Messages =====
    'no_conversations': {'ar': 'لا توجد محادثات بعد', 'en': 'No conversations yet'},
    'type_message': {'ar': 'اكتب رسالة...', 'en': 'Type a message...'},
    'new_message': {'ar': 'رسالة جديدة', 'en': 'New Message'},
    'select_recipient': {'ar': 'اختر المستلم', 'en': 'Select Recipient'},
  };

  static String t(bool isArabic, String key) {
    final entry = _strings[key];
    if (entry == null) return key;
    return entry[isArabic ? 'ar' : 'en'] ?? key;
  }
}